apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: car-dealer-app-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
